Feature/jc 600 redesigned book catalog page
saritasa-nest/camp-js-2024-angelina-shmantsar pull request #1
Opened 2024-07-04 12:31 UTC by AngelinaShmantsar

2024-07-05 12:57 UTC, artem-sotnichenko-saritasa commented
Hi, don't have much time this week, so just a quick design review for now. I will review your code thoroughly next week. 

1. Please make your markup fluid. 
Check the video example. It has display grid applied this way: show maximum amount of cards with minimum with of card=180px. It explained in the article I listed with css lecture in slack.
In your app, there are white space on the sides, when changing page size.

https://github.com/saritasa-nest/camp-js-2024-angelina-shmantsar/assets/98300391/b34aacc4-68ef-45a8-b064-b3744d723634

2. Please make that card titles are cut if over two lines. Like so:
![image](https://github.com/saritasa-nest/camp-js-2024-angelina-shmantsar/assets/98300391/ec9bb1f1-adc3-4494-a4ba-f87d087e523c)

3. Please pay more attention to font styles and spacings. Some of them are not aligned with Figma.
I understand that's hard to do it pixel-perfect. But if you build such habit now, you'll gain more experience faster, and you will spend less time doing markups in the future.

Overall, you did a good job!

2024-07-09 09:19 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/global/components.css
> +	top: 65px;
It's a good practice to calculate such values. It improves maintainability and understandability. 

Example:
```css
top: calc(var(--header-height) + var(--border-width));
```
_Both variables should be global for this to work properly._

2024-07-09 09:19 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/global/components.css
> +.books p {
When using BEM methodology, your CSS selectors should always have a single class. In this case, it's should probably be `.book__title`.

2024-07-09 09:19 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/global/components.css
> +	text-transform: var(--uppercase);
It's meaningless, because `--uppercase` can only be `uppercase`.

It would make sense to have `--subtitle-text-transform` variable be `uppercase`. Variable's value can change, but variable's purpose/meaning shouldn't change.

But in our task, I think it's okay to just `text-transform: uppercase`.

2024-07-09 09:19 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/global/components.css
> +	background-position: 95% 12px;
This way it'll always be `12px` from the right edge.  
```suggestion
  background-position: calc(100% - 12px) 12px;
```

2024-07-09 09:19 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/global/components.css
> +	}
I think it's a good case to use `grid` and `repeat(3, 1fr)`

2024-07-09 09:19 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/global/variables.css
>  :root {
Let's group variables by it's purposes. Also, please remove unused variables and pages.

2024-07-09 09:19 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/pages/static/heroicons_chevron-down.png
Prefer storing icons in SVG format. Less size, no quality loss.

2024-07-09 09:19 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/global/components.css
> +	margin: 0 24px;
It's a good practice to extract sizes into tokens. It improves consistency and allows easily changing them.
In designs, I used 4px based sizes.

First is more flexible, but less descriptive than second. I personally prefer first for sizes, and second for shadows, border-radiuses, etc.

```
--size-1: 4px;
--size-2: 8px;
--size-3: 12px;
--size-4: 16px;
...

```
Or
```
--size-xs: 4px;
--size-sm: 8px;
--size-md: 16px;
--size-lg: 24px;
--size-xl: 32px;
--size-2xl: 40px;
...
```

2024-07-09 09:47 UTC, SofyaKirillova requested changes

2024-07-09 09:47 UTC, SofyaKirillova commented on apps/vanilla/src/global/variables.css
> +	--heading-color-3: #b0e0e6;
These variables are not used anywhere

2024-07-09 09:47 UTC, SofyaKirillova commented on apps/vanilla/src/global/variables.css
> +	--border-color: rgb(0 0 0 / 15%);
Let's use one color model rgb or hexadecimal

2024-07-09 09:47 UTC, SofyaKirillova commented on apps/vanilla/src/global/variables.css
> +	--uppercase: uppercase;
I think it's better to delete this variable, because it doesn't carry any semantic load.

2024-07-09 09:47 UTC, SofyaKirillova commented on apps/vanilla/src/pages/example/example.css
Let's delete this file

2024-07-09 09:47 UTC, SofyaKirillova commented on apps/vanilla/src/pages/example/nested/nested.css
Let's delete this file

2024-07-09 09:47 UTC, SofyaKirillova commented on apps/vanilla/src/pages/index.css
>  .title {
This class isn't used anywhere

2024-07-09 09:47 UTC, SofyaKirillova commented on apps/vanilla/src/pages/index.html
> +						<span>© 2023</span>
```suggestion
						<span>&copy; 2023</span>
```

2024-07-09 09:47 UTC, SofyaKirillova commented on apps/vanilla/src/pages/static/heroicons_chevron-down.png
It is better to use icons in svg format, as they are smaller in size

2024-07-09 09:47 UTC, SofyaKirillova commented on apps/vanilla/src/global/components.css
These are not global styles, let's move them to the pages folder

2024-07-09 09:47 UTC, SofyaKirillova commented on apps/vanilla/src/global/components.css
> +	height: 64px;
This value is used in several places, if they are related, then put it in a separate variable

2024-07-09 09:47 UTC, SofyaKirillova commented on apps/vanilla/src/global/components.css
> +	/* stylelint-disable-next-line value-no-vendor-prefix */
If you disable the rules, always add a comment on why you are doing this

2024-07-09 09:47 UTC, SofyaKirillova commented on apps/vanilla/src/global/components.css
> +	width: 320px;
This value is used in several places, if they are related, then put it in a separate variable

2024-07-09 09:47 UTC, SofyaKirillova commented on apps/vanilla/src/global/components.css
> +	top: 65px;
This value is used in several places, if they are related, then put it in a separate variable

2024-07-09 09:47 UTC, SofyaKirillova commented on apps/vanilla/src/global/components.css
> +	height: 48px;
This value is used in several places, if they are related, then put it in a separate variable

2024-07-09 09:47 UTC, SofyaKirillova commented on apps/vanilla/src/global/components.css
> +	background-image: url("../pages/static/heroicons_magnifying-glass.png");
Why are `background-colors` and `background-image` used at the same time?

2024-07-09 09:47 UTC, SofyaKirillova commented on apps/vanilla/src/global/components.css
> +@media screen and (max-width: 1919px) {
Let's round up the value

2024-07-09 09:47 UTC, SofyaKirillova commented on apps/vanilla/src/global/components.css
> +@media screen and (max-width: 1279px) {
Let's round up the value

2024-07-09 09:47 UTC, SofyaKirillova commented on apps/vanilla/src/global/components.css
> +		top: 228px;
Let's put this in a variable and give it a name that explains what we use it for, so improving the readability of the code

2024-07-09 09:47 UTC, SofyaKirillova commented on apps/vanilla/src/global/components.css
> +		width: 30%;
This value is used in several places, if they are related, then put it in a separate variable

2024-07-09 09:54 UTC, SofyaKirillova requested changes
![image](https://github.com/saritasa-nest/camp-js-2024-angelina-shmantsar/assets/108254953/69429af7-871e-493d-bbc0-d17b026ec30d)

You don't have a line

2024-07-09 10:34 UTC, maxineo commented on apps/vanilla/src/global/components.css
> +.filters {
Lets move the block above its elements. That way it will be easier to follow the structure.

2024-07-09 10:34 UTC, maxineo commented on apps/vanilla/src/pages/index.html
> +								<img class="book__image" src="static/image3.png" alt="book-cover">
Ideally you should provide some meaningful text for `alt` attribute, so lets instead use books names.

2024-07-09 10:34 UTC, maxineo commented on apps/vanilla/src/pages/static/heroicons_chevron-down.png
Additionally you can use https://svgomg.net/ to make them even smaller.

2024-07-10 06:16 UTC, AngelinaShmantsar commented on apps/vanilla/src/pages/index.html
> +						<span>© 2023</span>
But [this article](https://github.com/hail2u/html-best-practices?tab=readme-ov-file#dont-use-character-references-as-much-as-possible) says the opposite. How to do it better?

2024-07-10 06:54 UTC, AngelinaShmantsar commented on apps/vanilla/src/global/components.css
> +	background-image: url("../pages/static/heroicons_magnifying-glass.png");
We need to set both `background-color` and `background-image` for this input. Default input element does not have any background color. The image is needed due to design

2024-07-10 11:54 UTC, artem-sotnichenko-saritasa approved these changes

2024-07-10 11:54 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/pages/static/image 1.svg
It's useless to use SVGs for raster graphics. In such case, it's basically png wrapped around svg, so size would be the same. 

As a rule of thumb, use svg for icons, use png/jpg/webp for content images.

2024-07-10 11:54 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/pages/task1/variables.css
> +	--size-2xl: 40px;
Let's name it more meaningfully `--border-radius-xs: 4px`

2024-07-10 11:54 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/pages/index.css
> +	color: var(--heading-color-1);
Looks like you don't have such variable, maybe you forgot to remove this styles?

2024-07-10 12:03 UTC, AngelinaShmantsar commented on apps/vanilla/src/pages/index.css
> +	color: var(--heading-color-1);
Nope, i don't forget to remove these styles. They are for the main page. `--heading-color-1` variable is in `src/global/variables.css` file. I moved page and styles for this task to separate folder

2024-07-10 13:09 UTC, maxineo approved these changes

2024-07-10 13:09 UTC, maxineo commented on apps/vanilla/src/pages/task1/index.html
> +							</article>
Articles belong to sectioning content, therefore should have a heading inside.
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/article#usage_notes
https://developer.mozilla.org/en-US/docs/Web/HTML/Content_categories#sectioning_content

2024-07-11 03:08 UTC, SofyaKirillova requested changes
![image](https://github.com/saritasa-nest/camp-js-2024-angelina-shmantsar/assets/108254953/4a103d47-a614-44a8-a75f-24cdf6873588)
![image](https://github.com/saritasa-nest/camp-js-2024-angelina-shmantsar/assets/108254953/12cdfdd2-018e-4220-a33e-5f76585aa44e)

In some places we see some of the image

2024-07-11 03:08 UTC, SofyaKirillova commented on apps/vanilla/src/pages/task1/variables.css
> +	--size-2xl: 40px;
Let's delete the variables that we don't use

2024-07-11 03:08 UTC, SofyaKirillova commented on apps/vanilla/src/pages/task1/index.html
> +				<div class="filters-wrapper">
![image](https://github.com/saritasa-nest/camp-js-2024-angelina-shmantsar/assets/108254953/ad47bf42-8f80-462b-95d3-a8738dc790b6)

The height of the footer does not match the dimensions
Let's add box-sizing: border-box; for all elements

border-box tells the browser to account for any border and padding in the values you specify for an element's width and height

2024-07-11 05:27 UTC, AngelinaShmantsar commented on apps/vanilla/src/pages/task1/index.html
> +			<footer class="books-app-footer">
Is this relevant to the comment about `box-sizing`?

2024-07-11 07:01 UTC, SofyaKirillova commented on apps/vanilla/src/pages/task1/index.html
> +			<footer class="books-app-footer">
Yes

2024-07-11 07:05 UTC, SofyaKirillova requested changes

2024-07-11 07:05 UTC, SofyaKirillova commented on apps/vanilla/src/pages/task1/index.html
> +<!DOCTYPE html>
![image](https://github.com/saritasa-nest/camp-js-2024-angelina-shmantsar/assets/108254953/4a103d47-a614-44a8-a75f-24cdf6873588)
![image](https://github.com/saritasa-nest/camp-js-2024-angelina-shmantsar/assets/108254953/12cdfdd2-018e-4220-a33e-5f76585aa44e)

In some places we see some of the image

2024-07-11 08:17 UTC, AngelinaShmantsar commented on apps/vanilla/src/pages/task1/index.html
> +<!DOCTYPE html>
I can't reproduce this bug... There are borders only
![2024-07-11 в 13 12 16](https://github.com/saritasa-nest/camp-js-2024-angelina-shmantsar/assets/174324767/f0a51696-22ef-444f-95dc-61676256cd09)
Should i open solution in another browser? I used Firefox

2024-07-11 08:40 UTC, SofyaKirillova commented on apps/vanilla/src/pages/task1/index.html
> +<!DOCTYPE html>
This is in the Chrome browser

Please, always test applications in Chrome, as it is the most popular

2024-07-11 08:47 UTC, AngelinaShmantsar commented on apps/vanilla/src/pages/task1/index.html
> +<!DOCTYPE html>
Okay, thanks, i'll test it in Chrome

2024-07-12 07:52 UTC, SofyaKirillova requested changes
![image](https://github.com/user-attachments/assets/768d6739-0f70-4b55-8824-0a1c2f36eb3b)
Part of the image is not visible

2024-07-14 06:09 UTC, SofyaKirillova approved these changes

2024-07-15 04:06 UTC, merged