Feature/jc 643 initialize anime app
saritasa-nest/camp-js-2024-angelina-shmantsar pull request #3
Opened 2024-07-17 11:49 UTC by AngelinaShmantsar

2024-07-17 13:38 UTC, shalomich requested changes

2024-07-17 13:38 UTC, shalomich commented on apps/angular/src/app/features/animeTable/animeTable.component.ts
> +			.subscribe(value => (this.anime = value));
Please subscribe only in `ngOnInit`

2024-07-17 13:38 UTC, shalomich commented on apps/angular/src/app/features/animeTable/animeTable.component.ts
> +			.subscribe(value => (this.anime = value));
Please subscribe to the anime list in template using `async` pipe https://metanit.com/web/angular2/8.4.php

2024-07-17 13:38 UTC, shalomich commented on apps/angular/src/core/dtos/backendEnums/animeStatusEnum.ts
> +export enum AnimeStatusEnum {
I think `Enum` preffix is  redudant

2024-07-17 13:38 UTC, shalomich commented on apps/angular/src/core/dtos/backendEnums/animeStatusEnum.ts
> +	NOT_YET_AIRED,
We use snake case only for constants, not enums. Did you mean that:
```suggestion
	NotYetAired = 'NOT_YET_AIRED',
```

2024-07-17 13:38 UTC, shalomich commented on apps/angular/src/core/mappers/anime.mapper.ts
> +		return new Anime(dto);
Mapping usually takes place inside this method, not inside the model constructor. If I'm not mistaken, the constructor approach is no longer used on projects

2024-07-17 13:38 UTC, shalomich commented on apps/angular/src/core/interfaces/dateTimeRangeField.ts
> +export type DateTimeRangeField = {
`interfaces` is strange folder. Let's place it in models folder

2024-07-17 13:38 UTC, shalomich commented on apps/angular/src/core/models/anime.ts
> +export class Anime {
Did someone ask you to use a class for models? We usually use interface or type

2024-07-17 13:38 UTC, shalomich commented on apps/angular/src/core/services/anime.service.ts
> +	private baseAnimeUrl = `${BASE_API_URL}anime/`;
I suggest creating urls in a separate service

2024-07-17 13:38 UTC, shalomich commented on apps/angular/src/core/services/anime.service.ts
> +				// eslint-disable-next-line @typescript-eslint/naming-convention
Please use eslint-disable as rarely as possible, only in special cases

2024-07-17 13:38 UTC, shalomich commented on apps/angular/src/core/services/anime.service.ts
> +				aired: {
Why is mapping not happening in the mapper?

2024-07-17 13:38 UTC, shalomich commented on apps/angular/src/core/services/anime.service.ts
> +	private mapAnimeDto(dto: AnimeDto[]): Anime[] {
I think we can do without this method.

2024-07-17 13:38 UTC, shalomich commented on apps/angular/src/core/services/anime.service.ts
> +				'Api-Key': 'a392e76c-bd9b-4e37-a0cb-82f6aa60bb72',
I think we need to add for each backend request, not just for this one. And copying this line all the time is not the best idea.

2024-07-17 13:38 UTC, shalomich commented on libs/core/dtos/pagination.dto.ts
> -export interface PaginationDto<T> {
Why did you decide to change interface to type everywhere?

2024-07-17 13:38 UTC, shalomich commented on apps/angular/src/core/utils/convertIsoToLocale.ts
> +export function convertIsoToLocale(isoString: string): string {
As if you can do without this function. But you can leave it at your discretion

2024-07-17 13:38 UTC, shalomich commented on apps/angular/src/app/app-routing.module.ts
> -export class AppRoutingModule {}
Why do you delete this?

2024-07-17 13:38 UTC, shalomich commented on apps/angular/src/app/app.module.ts
> -export class AppModule {}
Same

2024-07-17 15:24 UTC, maxineo requested changes
Lets also fix UI. Table header, `status` and `type` columns are not really user friendly.
![image](https://github.com/user-attachments/assets/0fb11d24-a293-4952-842c-8d718e25dbd8)

2024-07-17 15:24 UTC, maxineo commented on apps/angular/src/core/mappers/anime.mapper.ts
> +		return new Anime(dto);
Roman is correct. Constructor should be used to create and initialize the object. Mapping should be done here.

What if you need to create a model inside you app, but you have no dto?

2024-07-17 15:24 UTC, maxineo commented on apps/angular/src/core/models/anime.ts
> +	public readonly modified: string;
Lets use `Date` for date fields.

2024-07-17 15:24 UTC, maxineo commented on apps/angular/src/core/models/anime.ts
> +	public readonly genres: number[];
```suggestion
	/** Studios. */
	public readonly studios: readonly number[];

	/** Genres. */
	public readonly genres: readonly number[];
```

2024-07-17 15:24 UTC, maxineo commented on apps/angular/src/core/models/anime.ts
> +export class Anime {
We switched to types not long ago, but they both have its own pros and cons.

2024-07-17 15:24 UTC, maxineo commented on apps/angular/src/core/services/anime.service.ts
> +	private httpClient = inject(HttpClient);
```suggestion
	private readonly httpClient = inject(HttpClient);
```

2024-07-17 15:24 UTC, maxineo commented on apps/angular/src/core/services/anime.service.ts
> +	public constructor() {}
You can omit empty constructor.

2024-07-17 15:24 UTC, maxineo commented on apps/angular/src/core/services/anime.service.ts
> +	public getAllAnime(): Observable<Anime[]> {
`Anime` is a useless prefix. When we are dealing with `AnimeService` its obvius that `getAll` or `getOne` will return anime.

2024-07-17 15:24 UTC, maxineo commented on apps/angular/src/core/services/anime.service.ts
> +				'Api-Key': 'a392e76c-bd9b-4e37-a0cb-82f6aa60bb72',
You can use [interceptors](https://v17.angular.io/api/common/http/HttpInterceptor) for this.

2024-07-17 15:24 UTC, maxineo commented on apps/angular/src/core/services/anime.service.ts
> +	private mapAnimeDto(dto: AnimeDto[]): Anime[] {
I agree that we dont really need this method, just dont forget about immutability.
```suggestion
	private mapAnimeDto(dto: readonly AnimeDto[]): Anime[] {
```

2024-07-17 15:24 UTC, maxineo commented on apps/angular/src/core/services/anime.service.ts
> +					end: item.aired.end,
Its strange that we only need to convert one of the dates.

As far as I understand you are doing it to display it in correct way in UI.
In this case your model depends on UI.

As I mentioned before change it to Date objects, than you can use `Date` pipe from angular.
https://v17.angular.io/api/common/DatePipe

2024-07-17 15:24 UTC, maxineo commented on apps/angular/src/theme/variables.css
> +	--table-image-height: 150px;
Do we really need these as global variables? It looks like they are specific to anime table only.

2024-07-17 15:24 UTC, maxineo commented on apps/angular/src/core/dtos/getAnimeResponse.dto.ts
> +export type GetAnimeResponseDto = {
Looks like you can use `Pagination` from `core` instead of this type.

2024-07-18 05:58 UTC, AngelinaShmantsar commented on libs/core/dtos/pagination.dto.ts
> -export interface PaginationDto<T> {
Because using interfaces caused linter errors

2024-07-18 06:04 UTC, AngelinaShmantsar commented on apps/angular/src/app/app-routing.module.ts
> -export class AppRoutingModule {}
Because it was necessary to make all the components standalone. It was a task about migrating angular project to standalone components

2024-07-18 06:04 UTC, AngelinaShmantsar commented on apps/angular/src/app/app.module.ts
> -export class AppModule {}
Because it was necessary to make all the components standalone. It was a task about migrating angular project to standalone components

2024-07-18 06:44 UTC, AngelinaShmantsar commented on apps/angular/src/app/features/animeTable/animeTable.component.html
> +<div class="anime-table-wrapper">
I used this wrapper to scroll the table itself, not the entire page
![localhost_4200_](https://github.com/user-attachments/assets/be336fb9-d5a5-42fe-8bb4-036752178910)

2024-07-18 19:17 UTC, maxineo commented on apps/angular/src/app/features/animeTable/animeTable.component.ts
> +	}
You dont have to do it this way. You are not subscribing to it, but just getting the observable from the service. You could do it like this:

`protected readonly anime$ = this.animeService.getAll();`

In general I suggest not to initialize class proprties in lifecycle hooks. This is supposed to be done in constructor.

2024-07-18 19:17 UTC, maxineo commented on apps/angular/src/core/dtos/backendEnums/animeStatus.dto.ts
> +export type AnimeStatusDto = {
Im not sure why you decided to change it to object. You are trying to simulate enum, so lets instead use actual enum for it.

If you have any troubles with it, feel free to dm me.

2024-07-18 19:17 UTC, maxineo commented on apps/angular/src/core/interceptors/apiKey.interceptor.ts
> + */
```suggestion
/**
 * Add 'Api-Key' header to request.
 * @param req - Request.
 * @param next - Next interceptor.
 */
```

2024-07-18 19:17 UTC, maxineo commented on apps/angular/src/core/interceptors/apiKey.interceptor.ts
> +			'a392e76c-bd9b-4e37-a0cb-82f6aa60bb72',
I believe this key is also environment sensitive, so lets move it into env file.

2024-07-18 19:17 UTC, maxineo commented on apps/angular/src/core/mappers/anime.mapper.ts
> +export namespace AnimeMapper {
Lets use angular service for mappers.

2024-07-18 19:17 UTC, maxineo commented on apps/angular/src/core/mappers/anime.mapper.ts
> +		return anime;
```suggestion
		return {
			id: dto.id,
			created: dto.created,
			modified: dto.modified,
			titleEng: dto.title_eng,
			titleJpn: dto.title_jpn,
			image: dto.image,
			aired: dto.aired,
			type: dto.type,
			status: dto.status,
			score: dto.score,
			userScore: dto.user_score,
			studios: dto.studios,
			genres: dto.genres,
		};
```

2024-07-18 19:17 UTC, maxineo commented on apps/angular/src/core/models/anime.ts
> +	readonly genres: readonly number[];
These are IDs I guess? If so, lets name them properly and update jsdoc.

2024-07-18 19:17 UTC, maxineo commented on apps/angular/src/core/services/url.service.ts
> +export class UrlService {
```suggestion
export class ApiUrlService {
```

2024-07-18 19:17 UTC, maxineo commented on apps/angular/src/core/services/url.service.ts
> +	}
You can use getter for this.

2024-07-19 05:46 UTC, AngelinaShmantsar commented on apps/angular/src/app/features/animeTable/animeTable.component.html
> +<div class="anime-table-wrapper">
Yes, the problem is in the picture above. The title ends before the table (white rectangle in top right)

2024-07-19 05:50 UTC, AngelinaShmantsar commented on apps/angular/src/app/features/animeTable/animeTable.component.css
> +[mat-header-cell],
Because this is an attribute selector

2024-07-19 10:21 UTC, maxineo commented on apps/angular/src/app/features/animeTable/animeTable.component.css
> +[mat-header-cell],
Ah, I see :)

2024-07-19 12:23 UTC, maxineo commented on apps/angular/src/app/features/animeTable/animeTable.component.html
> +		<ng-container matColumnDef="image">
Lets try to reuse columns from component's class. Currently you have to duplicate columns in template.

2024-07-19 12:23 UTC, maxineo commented on apps/angular/src/app/features/animeTable/animeTable.component.ts
> +	protected readonly displayedColumns: readonly string[] = ['image', 'title_eng', 'title_jpn', 'aired_start', 'type', 'status'];
Lets be consistent and use camelCase for columns.

Also I propose to use the exact same spelling as in your models. From my experience there will be issues with sorting if the spelling is different.

2024-07-19 12:23 UTC, maxineo commented on apps/angular/src/core/mappers/animeStatus.mapper.ts
> +/** Anime status transform service. */
```suggestion
/** Anime status mapper. */
```

2024-07-19 12:23 UTC, maxineo commented on apps/angular/src/core/mappers/anime.mapper.ts
> +/** Anime dto transform service. */
It can possibly map many things, not only DTO
```suggestion
/** Anime mapper. */
```

2024-07-19 12:23 UTC, maxineo commented on apps/angular/src/core/mappers/animeType.mapper.ts
> +/** Anime type transform service. */
```suggestion
/** Anime type mapper. */
```

2024-07-19 12:23 UTC, maxineo commented on apps/angular/src/core/mappers/animeStatus.mapper.ts
> +	private readonly fromAnimeStatusDto: Readonly<Record<AnimeStatusDto, AnimeStatus>> = {
Its not necessary to make it a class property. You can simply make it a constant. Imho it will make the class more readable.

2024-07-19 12:23 UTC, maxineo commented on apps/angular/src/core/services/anime.service.ts
> +	/** Fetch all anime from backend. */
Lets not describe unnecessary internal logic of the method. Does it really matter for the consumer whether the method fetches it from BE or gets the data somewhere else?

2024-07-19 12:23 UTC, maxineo commented on apps/angular/src/core/services/anime.service.ts
> +})
```suggestion
/** Anime service. */
@Injectable({ providedIn: 'root' })
```

2024-07-19 12:23 UTC, maxineo commented on apps/angular/src/core/services/apiUrl.service.ts
> +	}
I suggest you to think how to organize urls better. It took you 7 lines to add a single URL. What if there are hundreds of URLs? This service will be a nightmare to work with.

2024-07-19 12:32 UTC, maxineo commented
I also noticed that you use camelCase for file names. In angular apps you should use kebab-case for files. Thats described in [angular style guide](https://angular.dev/style-guide#separate-file-names-with-dots-and-dashes).

2024-07-22 04:05 UTC, AngelinaShmantsar commented on apps/angular/src/app/features/animeTable/animeTable.component.html
> +<div class="anime-table-wrapper">
Thanks, it worked!

2024-07-22 05:34 UTC, artem-sotnichenko-saritasa approved these changes

2024-07-22 05:34 UTC, artem-sotnichenko-saritasa commented on apps/angular/src/app/features/animeTable/animeTable.component.css
> +	--table-border-color: rgb(138 43 226);
Let's be a bit more specific, it's not obvious is it background or text colors

2024-07-22 05:34 UTC, artem-sotnichenko-saritasa commented on apps/angular/src/core/dtos/anime.dto.ts
> +	readonly created: Date;
It's not true that you're getting `Date` from the API. Actually, API returns string in ISO format, like so "2024-07-16T08:42:57.137313Z".

Please, update types, mapping and jsdoc accordingly. It's good practice to include date string format in jsdoc.

2024-07-22 05:34 UTC, artem-sotnichenko-saritasa commented on apps/angular/src/core/mappers/anime.mapper.ts
> +			modified: dto.modified,
Currently, types for `created`, `modified`, and `aired` are wrong. 
It should be `Date`, but if you would try to use any of `Date`'s methods, for example `.getTime()`, it will result in runtime error.

2024-07-22 05:34 UTC, artem-sotnichenko-saritasa commented on libs/core/dtos/pagination.dto.ts
> -export interface PaginationDto<T> {
We started to prefer `type`s over `interface`s not long ago. So it's right choice to use `type` in the new project.

2024-07-22 12:34 UTC, maxineo commented on apps/angular/src/core/models/anime.ts
> +	readonly created: string;
Thats not what Artem meant. You should still use `Date` in your model for reasons I specified in my earlier comments.

You can map the data in the mapper however you want. Thats one of the benefits of using DTO pattern.

2024-07-22 12:34 UTC, maxineo commented on apps/angular/src/core/models/date-time-range.ts
> +	 * @type {/\d{4}-[01]\d-[0-3]\dT[0-2]\d:[0-5]\d:[0-5]\d\.\d+([+-][0-2]\d:[0-5]\d|Z)/}
I love regexs, but using it as a type is unlikely to help the user of this model.

2024-07-22 12:34 UTC, maxineo commented on apps/angular/src/core/models/date-time-range.ts
> +	readonly start: string;
Please use `Date` here as well.

2024-07-22 12:34 UTC, maxineo commented on apps/angular/src/core/services/api-url.service.ts
> +	private readonly _allAnimeUrl = `${baseApiUrl}${Endpoints.Anime}`;
I suggest you to group urls by their purpose or model:
```
  public readonly anime = {
    list: `${baseApiUrl}${Endpoints.Anime}`,
    ...
  }
```

2024-07-22 12:34 UTC, maxineo commented on apps/angular/src/core/services/api-url.service.ts
> +const { baseApiUrl } = environment;
I suggest you to add `AppConfig` service to work with env variables.

2024-07-22 12:34 UTC, maxineo commented on apps/angular/src/core/services/api-url.service.ts
> +}
Im not sure its worth to use enum for endpoints. I dont think they are going to be reused. So I suggest you to simply write them where you construct the url.

2024-07-22 12:34 UTC, maxineo commented on apps/angular/src/core/services/api-url.service.ts
> +	private readonly _allAnimeUrl = `${baseApiUrl}${Endpoints.Anime}`;
Lets add a method to unify construction of api urls for later endpoints.

2024-07-23 09:50 UTC, maxineo approved these changes

2024-07-23 09:50 UTC, maxineo commented on apps/angular/src/core/models/table-column-key.ts
> +/** Column key values. */
These keys are specific to Anime table. So lets move it there.

2024-07-23 09:50 UTC, maxineo commented on apps/angular/src/core/models/table-column.ts
> +	readonly key: ColumnKey;
Lets add generic to make this model reusable in the future.

2024-07-23 09:50 UTC, maxineo commented on apps/angular/src/core/models/table-column.ts
> +export type Column = {
```suggestion
export type TableColumn = {
```

2024-07-23 09:50 UTC, maxineo commented on apps/angular/src/core/services/api-url.service.ts
> +	public get allAnimeUrl(): string {
Such getters add no real benefits, but add a lot of boilerplate code. I suggest remove it and simply make `anime` property public.

2024-07-23 09:50 UTC, maxineo commented on apps/angular/src/core/services/api-url.service.ts
> +	private readonly anime: Readonly<Record<string, string>> = {
I suggest to remove typing and let TS infer type itself. You are not necessarily going to work with strings only.

2024-07-23 09:54 UTC, maxineo commented
Btw, you have core library, I believe your `Anime` models are not app specific, and therefore should be placed there.

2024-07-24 05:17 UTC, shalomich approved these changes

2024-07-24 05:17 UTC, shalomich commented on apps/angular/src/app/features/anime-table/anime-table.component.html
> +					@case ('image') {
Can we use enum `ColumnKey` in `@case`? Otherwise, you can change the string in one place and forget it in another.
```suggestion
					@case (columnKey.Image ) {
```

To do this, add the field to the component:

`protected columnKey = ColumnKey;`

2024-07-24 05:17 UTC, shalomich commented on apps/angular/src/app/features/anime-table/anime-table.component.ts
> +	protected readonly headerRowDef = this.displayedColumns.map(column => column.key);
Please don't use abbreviations other than the generally accepted ones (for example, DTO). If I had seen this field in the template, I would hardly have understood what it means and would have had to go to the component to read the comment.

```suggestion
	protected readonly headerRowDefinitions = this.displayedColumns.map(column => column.key);
```

2024-07-25 06:51 UTC, danilkukryakov requested changes

2024-07-25 06:51 UTC, danilkukryakov commented on apps/angular/src/app/features/anime-table/anime-table.component.css
> +}
We try to [follow](https://wiki.saritasa.rocks/frontend/languages/css/#bem) BEM conventions in our code. That's why we prefer class CSS selectors over tag or attribute selectors. Please, replace attribute selectors in your code.

2024-07-25 06:51 UTC, danilkukryakov commented on apps/angular/src/app/features/anime-table/anime-table.component.ts
> +	protected columnKey = ColumnKey;
We can make this property `readonly`:
```suggestion
	/** Column key. */
	protected readonly columnKey = ColumnKey;
```

2024-07-25 06:51 UTC, danilkukryakov commented on apps/angular/src/core/dtos/anime.dto.ts
> +/* eslint-disable @typescript-eslint/naming-convention */
You can adjust your ESLint configuration to disable this rule for all *.dto.ts files.
In our projects we usually have the following option in `.eslintrc.json`:
```json
{
  "files": ["*.dto.ts", "*.mapper.ts"],
  "rules": {
    "@typescript-eslint/naming-convention": "off"
  }
},
```

2024-07-25 06:51 UTC, danilkukryakov commented on apps/angular/src/core/dtos/anime.dto.ts
> +	readonly created: string;
I think 'type' is redundant here since we have TypeScript in the project. Let's omit this:
```suggestion
	 * String in ISO date format.
	 */
	readonly created: string;
```

2024-07-25 06:51 UTC, danilkukryakov commented on apps/angular/src/core/dtos/anime.dto.ts
> +	readonly created: string;
Please, apply this change everywhere.

2024-07-25 06:51 UTC, danilkukryakov commented on apps/angular/src/core/dtos/anime.dto.ts
> +	readonly image: string;
Let's add some clarification whether about the image.
I guess, it's a link to image.
It might be important because in some cases we might get image encoded in base64 or path on the server instead of a link (or something else).
```suggestion
	/** Anime poster image URL. */
	readonly image: string;
```

2024-07-25 06:51 UTC, danilkukryakov commented on apps/angular/src/core/dtos/anime.dto.ts
> +	readonly genres: readonly number[];
I guess we have an array of identifiers here:
```suggestion
	/** Studio IDs. */
	readonly studios: readonly number[];

	/** Genre IDs. */
	readonly genres: readonly number[];
```

2024-07-25 06:51 UTC, danilkukryakov commented on apps/angular/src/core/interceptors/api-key.interceptor.ts
> +	const apiKeyReq = req.clone({
Try to avoid contractions. See our [wiki](https://wiki.saritasa.rocks/frontend/languages/ts-js/naming#avoid-contractions) for additional details:
```suggestion
	const apiKeyRequest = req.clone({
```

2024-07-25 06:51 UTC, danilkukryakov commented on apps/angular/src/core/mappers/anime-status.mapper.ts
> +export class AnimeStatusMapper {
This mapper is correct from Angular perspective. We write mappers like this on our Angular projects.
However, you have project with two frameworks - Angular and React. Both will use the same models, DTOs and mappers.
To save time we have to use framework agnostic approach, so we can reuse our code in both Angular and React.
That's why you should rework your mappers a bit. To be framework agnostic you can use namespace mappers. You already have one in the project, see libs/core/mappers/genre.mapper.ts for reference.

Please, rework all mappers in your project using namespaces.

2024-07-25 06:51 UTC, danilkukryakov commented on apps/angular/src/core/models/anime.ts
> +	readonly titleJpn: string;
Please, [avoid](https://wiki.saritasa.rocks/frontend/languages/ts-js/naming#avoid-contractions) contractions:
```suggestion
	/** Anime title in English. */
	readonly titleEnglish: string;

	/** Anime title in Japanese. */
	readonly titleJapanese: string;
```

2024-07-25 06:51 UTC, danilkukryakov commented on apps/angular/src/core/models/anime.ts
> +	readonly image: string;
If this image is a link we can give a hint about it using property name. Besides, we can be more descriptive and use `poster` instead of generic 'image':
```suggestion
	/** Anime poster URL. */
	readonly posterUrl: string;
```
This is an example, you can use alternative naming if you wish.

2024-07-25 06:51 UTC, danilkukryakov commented on apps/angular/src/core/services/app-config.service.ts
> +	}
It seems like there are no benefits in using getter here. Let's rework it to make code simpler:
```suggestion
	/** 'baseApiUrl' environment variable. */
	public readonly baseApiUrl = environment.baseApiUrl;
```

2024-07-25 06:51 UTC, danilkukryakov commented on apps/angular/src/index.html
> +</head>
Fix code formatting here.

2024-07-25 06:51 UTC, danilkukryakov commented on apps/angular/src/core/models/anime.ts
> +	readonly userScore: number;
Just a suggestion (you may disagree with me) - 'score' and 'userScore' properties are a bit confusing.
Maybe use `criticScore` and `userScore` (or something like this)?

2024-07-25 06:51 UTC, danilkukryakov commented on apps/angular/src/app/features/anime-table/anime-table.component.html
> +						{{element.aired.start | date:"dd.MM.yyyy" | empty}}
I think you will display date in other components as well. Usually all dates are display in the same format for consistency.
In our projects we often create a constant variable for date format and use it everywhere. It will look like this:
```suggestion
						{{element.aired.start | date:dateFormat | empty}}
```

2024-07-25 06:51 UTC, danilkukryakov commented on apps/angular/src/app/features/app-header/app-header.component.ts
'app-header' is a component not a feature.
For stuff like this we usually create `shared` folder. In this folder we can store reusable components for our app.
By the way, you already have such folder in your project. Let's move AppHeaderComponent there.

2024-07-25 06:51 UTC, danilkukryakov commented on apps/angular/src/app/features/app-header/app-header.component.ts
> +	selector: 'app-header',
It seems like you didn't use Angular CLI to generate your component.
I'm sure about it because your components don't have `camp` prefix.
Usually each Angular project should have a project prefix which is configured in angular.json (project.json in 'nx' workspace).
It's already configured correctly, just be sure to use Angular CLI to generate entities in your project.

If I'm not mistaken in the 'nx' environment we can access Angular CLI using `nx generate` command. You can find more information in the [docs](https://nx.dev/nx-api/angular/documents/nx-and-angular).

2024-07-29 04:04 UTC, danilkukryakov approved these changes

2024-07-30 04:10 UTC, merged