Feature/jc 653 anime list management
saritasa-nest/camp-js-2024-angelina-shmantsar pull request #4
Opened 2024-07-30 07:31 UTC by AngelinaShmantsar

2024-08-05 14:51 UTC, LocTran-saritasa requested changes
Beautiful background 👍 
Could you add changing the page limit? It's also a part of the pagination

2024-08-05 14:51 UTC, LocTran-saritasa commented on apps/angular/src/app/features/search-form/search-form.component.ts
> +	selector: 'search-form',
```suggestion
	selector: camp-search-form',
```

2024-08-05 14:51 UTC, LocTran-saritasa commented on apps/angular/src/app/features/search-form/search-form.component.ts
> +	});
You have only 1 control so `FormControl` is enough
```suggestion
	protected readonly searchControl = new FormControl(this.value);
```

2024-08-05 14:51 UTC, LocTran-saritasa commented on apps/angular/src/app/features/search-form/search-form.component.ts
> +	}
You can subscribe to the `searchControl.valuechanges` to handle the search value change
https://v17.angular.io/api/forms/AbstractControl#valueChanges

2024-08-05 14:51 UTC, LocTran-saritasa commented on apps/angular/src/core/services/navigation.service.ts
> +	public constructor(private readonly activatedRoute: ActivatedRoute) {}
please use `inject()` instead
`activatedRoute = inject(ActivatedRoute)`

2024-08-05 14:51 UTC, LocTran-saritasa commented on apps/angular/src/core/services/navigation.service.ts
> +	private removeUndefined(params: Readonly<Record<string, string>>): Readonly<Record<string, string>> {
Why we must remove `undefined` from a `Record<string, string>`? Maybe there are some mistakes in types?

2024-08-05 14:51 UTC, LocTran-saritasa commented on apps/angular/src/core/services/navigation.service.ts
> +		}
I think it doesn't work, `removeUndefined` doesn't mutate the `params` at all

2024-08-05 14:51 UTC, LocTran-saritasa commented on apps/angular/src/index.html
> +		<link href="https://fonts.googleapis.com/css2?family=Manrope:wght@200..800&family=Megrim&display=swap" rel="stylesheet">
Could you please check the indentation?

2024-08-05 14:51 UTC, LocTran-saritasa commented on apps/angular/src/app/features/anime-table/anime-table.component.ts
> +						limit: String(this.pageSize),
```suggestion
						limit: this.pageSize.toString(),
```

2024-08-05 14:51 UTC, LocTran-saritasa commented on apps/angular/src/app/features/anime-table/anime-table.component.ts
> +				this.dataSource = new MatTableDataSource(this.anime as Anime[]);
Why we need type casting here?

2024-08-05 14:51 UTC, LocTran-saritasa commented on apps/angular/src/app/features/anime-type-filter/anime-type-filter.component.html
> +		@for (option of filterOptions; track $index) {
```suggestion
		@for (option of filterOptions; track option.value) {
```

2024-08-05 14:51 UTC, LocTran-saritasa commented on apps/angular/src/app/features/search-form/search-form.component.html
> +		<input matInput placeholder="One Piece" type="search" class="search-input" formControlName="search" [value]="value">
You don't need to bind the [value] of  `input`, the form control already supported that as you set the initial value in `FormControl`
```suggestion
		<input matInput placeholder="One Piece" type="search" class="search-input" [formControl]="searchControl">
```

2024-08-06 04:12 UTC, khoanguyen-saritasa requested changes

2024-08-06 04:12 UTC, khoanguyen-saritasa commented on apps/angular/src/app/features/anime-table/anime-table.component.ts
> +	protected readonly filter = signal<readonly AnimeType[] | undefined>(undefined);
In this case, the initial value should be `null`, not `undefined`. Undefined means the variable has been declared, but its value has not been assigned. Null means an empty value or a blank value. In this case, you are assigning the initial value for the signal, and that's why you should use `null` here.

2024-08-06 04:12 UTC, khoanguyen-saritasa commented on apps/angular/src/app/features/anime-table/anime-table.component.ts
> +	}
I don't see you `unsubscribe` this source anywhere, this can lead to memory leak.

2024-08-06 04:12 UTC, khoanguyen-saritasa commented on apps/angular/src/app/features/anime-table/anime-table.component.ts
> +	}
There are many ways to unsubscribe from observable sources, but unsubscribing from each source individually is not a good approach if you have many sources. Therefore, I don't recommend this approach. Instead, you can check this article: [How to Unsubscribe from Observables in Angular (Many Ways)](https://dev.to/digitaldino/how-to-unsubscribe-from-observables-in-angular-many-ways-32c9). Approaches #2 and #3 are more reliable and convenient, as we only need to unsubscribe once.

2024-08-06 04:12 UTC, khoanguyen-saritasa commented on apps/angular/src/app/features/anime-type-filter/anime-type-filter.component.css
> +}
Please get rid of `::ng-deep`

2024-08-06 04:22 UTC, AngelinaShmantsar commented on apps/angular/src/core/services/anime.service.ts
> +		const clearedParams = JSON.parse(JSON.stringify(AnimeManagementParamsMapper.toDto(params)));
Here i remove possible `undefined` from fields, so that there are no requests like `?search=undefined`

2024-08-06 06:39 UTC, AngelinaShmantsar commented on apps/angular/src/app/features/anime-table/anime-table.component.ts
> +				this.dataSource = new MatTableDataSource(this.anime as Anime[]);
Because `this.anime` has `readonly` modifier and `MatTableDataSource` needs just `Anime[]` (mutable type)

2024-08-06 07:08 UTC, AngelinaShmantsar commented on apps/angular/src/app/features/anime-table/anime-table.component.ts
> +			.pipe(
What did you mean? Filters can only be selected from a list, and the search only works when you click a button. Were you talking about something like caching?

2024-08-06 07:22 UTC, LocTran-saritasa commented on apps/angular/src/app/features/anime-table/anime-table.component.ts
> +			.pipe(
Oh sorry, it's a wrong example since your search bar needs a submit button.
Let's look at your filter selection dropdown, if I want to select 5 types, I will click 5 times, then we don't want to fetch the API 5 times right?
It's not caching, just a small delay before you process the result of the value changes
checkout `debounceTime` of rxjs

2024-08-06 08:39 UTC, AngelinaShmantsar commented on apps/angular/src/app/features/anime-table/anime-table.component.ts
> +			.pipe(
Okay, thanks a lot!

2024-08-06 10:23 UTC, AngelinaShmantsar commented on apps/angular/src/app/features/anime-table/anime-table.component.ts
> +};
The server requires `aired__startswith`

2024-08-07 07:54 UTC, viktor-sakhno-saritasa requested changes

2024-08-07 07:54 UTC, viktor-sakhno-saritasa commented on apps/angular/src/app/app.component.html
> +	<router-outlet></router-outlet>
You can use self-closing tags.
```suggestion
	<camp-app-header />
	<router-outlet />
```

2024-08-07 07:54 UTC, viktor-sakhno-saritasa commented on apps/angular/src/app/features/anime-table/anime-table.component.css
> +	font-family: Manrope, sans-serif;
Let's move font-family to variable.

2024-08-07 07:54 UTC, viktor-sakhno-saritasa commented on apps/angular/src/app/features/anime-table/anime-table.component.ts
> +};
It's not a good solution, when your frontend component knows which backend query parameters exists. I think we need to move it to service or mapper.

2024-08-07 07:54 UTC, viktor-sakhno-saritasa commented on apps/angular/src/app/features/anime-table/anime-table.component.html
> +	<camp-search-form [value]="search()"></camp-search-form>
At the moment, our table does a lot of things - display list of items and contains filters. It would be better, if our components will be more independent of each other and won't take on many tasks. I suggest you move filters to parent component from table component.

2024-08-07 07:54 UTC, viktor-sakhno-saritasa commented on apps/angular/src/app/features/anime-table/anime-table.component.ts
> +	protected readonly search = signal<string | null>(null);
Why we can't use `''` like default empty value instead `null`?
```suggestion
	protected readonly search = signal('');
```

2024-08-07 07:54 UTC, viktor-sakhno-saritasa commented on apps/angular/src/app/features/anime-table/anime-table.component.ts
> +	private readonly pageSize = signal(25);
Usually, we create a constant variable above component class, for example `const INITIAIL_PAGE_SIZE = 25`;
```suggestion
	private readonly pageSize = signal(INITIAIL_PAGE_SIZE);
```

2024-08-07 07:54 UTC, viktor-sakhno-saritasa commented on apps/angular/src/app/features/anime-table/anime-table.component.ts
> +	private readonly destroyReference = inject(DestroyRef);
`destroyRef` will be enough.
```suggestion
	private readonly destroyRef = inject(DestroyRef);
```

2024-08-07 07:54 UTC, viktor-sakhno-saritasa commented on apps/angular/src/theme/control-styles.css
It's very hard to read this file, because this one contains a lot of styles related to different entities. Let's divide it and create separate CSS files for each component like `text-field.css`, `input.css`, `select.css`, etc.

2024-08-07 07:54 UTC, viktor-sakhno-saritasa commented on apps/angular/src/shared/components/app-header/app-header.component.css
> +	/* Because of form fields */
For me as a developer who recently joined for development, this comment is unclear, let's improve it.

2024-08-07 07:54 UTC, viktor-sakhno-saritasa commented on apps/angular/src/core/services/navigation.service.ts
> +	public navigate(endpoint: string, params?: Readonly<Record<string, string>>): void {
Endpoint - it's something related to BE, let's change it to `url`.

2024-08-07 07:54 UTC, viktor-sakhno-saritasa commented on apps/angular/src/core/services/navigation.service.ts
> +			})),
Why do we need to use `pipe` from activated route's query parameters, if we don't use value from this observable?

2024-08-07 07:54 UTC, viktor-sakhno-saritasa commented on apps/angular/src/app/features/search-form/search-form.component.ts
> +	@Input() public value: string | null = null;
We write it down with several lines.
```suggestion
	/** Value of search input. */
	@Input() 
	public value: string | null = null;
```

2024-08-07 07:54 UTC, viktor-sakhno-saritasa commented on apps/angular/src/app/features/search-form/search-form.component.ts
> +	@Output() public readonly searchValueEmitter = new EventEmitter<string | null>();
```suggestion
	/** Search value. */
	@Output() 
	public readonly searchValueEmitter = new EventEmitter<string | null>();
```

2024-08-07 07:54 UTC, viktor-sakhno-saritasa commented on apps/angular/src/app/features/search-form/search-form.component.html
> +<form class="search-form">
If you specified `type=submit` for the button, you should use `ngSubmit` method for the form.
```suggestion
<form class="search-form" (ngSubmit)="onSubmit()">
```

2024-08-07 07:54 UTC, viktor-sakhno-saritasa commented on apps/angular/src/app/features/search-form/search-form.component.html
> +	<button mat-fab type="submit" class="search-button" (click)="onSubmit($event)">
And then remove this redundant handler
```suggestion
	<button mat-fab type="submit" class="search-button">
```

2024-08-07 07:54 UTC, viktor-sakhno-saritasa commented on apps/angular/src/app/features/search-form/search-form.component.ts
> +		this.searchControl.patchValue(this.value);
If your `value` input value will be changed, your component doesn't patch the new value for the control. Because `ngOnInit` will trigger only once after component initialization. In this case, you can use input setter.

2024-08-07 07:54 UTC, viktor-sakhno-saritasa commented on apps/angular/src/app/features/search-form/search-form.component.ts
> +	@Input() public value: string | null = null;
```suggestion
	@Input() 
	public set value(v: string | null) {
	  if (v) {
	    this.searchControl.patchValue(v);
	  }
	}
```

2024-08-07 07:54 UTC, viktor-sakhno-saritasa commented on apps/angular/src/app/features/anime-type-filter/anime-type-filter.component.ts
> +	@Input() public values: readonly AnimeType[] = [];
Why this prop name is `values`? I see, the type of this prop is `AnimeType[]`, so, maybe it's `types`?

2024-08-07 07:54 UTC, viktor-sakhno-saritasa commented on apps/angular/src/app/features/anime-table/anime-table.component.ts
> +					this.paginator.pageIndex = this.pageNumber();
It's not a good solution to set variable inside `map` operator. It is implicit side effects. You need to make it explicit, for example, use `tap`.

2024-08-07 07:54 UTC, viktor-sakhno-saritasa commented on apps/angular/src/app/features/anime-table/anime-table.component.ts
> +				this.dataSource = new MatTableDataSource(value as Anime[]);
Why do we need `MatTableDataSource` at all? We can use list of anime directly and pass it to `[dataSource]="animeItems"`, for example.

2024-08-09 03:13 UTC, LocTran-saritasa commented on apps/angular/src/app/features/anime-table/anime-table.component.ts
> +				this.dataSource = new MatTableDataSource(this.anime as Anime[]);
Then you should use the spread operator `[...this.anime]` to create another object that is mutable
your `this.anime` is read-only, if you directly cast it as mutable, you are modifying the read-only object, which can lead to bug, imagine you use that read-only object at another place, you will be confused about why its value is mutated 😄

2024-08-09 03:18 UTC, LocTran-saritasa commented on apps/angular/src/core/services/anime.service.ts
> +		const clearedParams = JSON.parse(JSON.stringify(AnimeManagementParamsMapper.toDto(params)));
It looks a bit "illegal" to do that.
Please create a util function `compose-http-params`, this function receives the params object with undefined as an input and returns the `HttpParams`, in this function, you will create a `new HttpParams()` and append only what you need into it then return

2024-08-09 03:31 UTC, khoanguyen-saritasa approved these changes

2024-08-09 03:31 UTC, khoanguyen-saritasa commented on apps/angular/src/app/features/anime-table/anime-table.component.ts
> +};
Then you need to refactor this logic since the UI logic should not know anything about API related. We should do the work in the mapper layer.

2024-08-09 03:46 UTC, LocTran-saritasa commented on apps/angular/src/app/features/anime-table/anime-table.component.ts
> +	private readonly searchForm!: SearchFormComponent;
You can listen to your emitter by its output from the template
`<camp-search-form (searchValueEmitter)="onChange($event)" />`
instead of using `@ViewChild` to access its properties

2024-08-09 03:46 UTC, LocTran-saritasa commented on apps/angular/src/app/features/anime-table/anime-table.component.ts
> +						`-${COLUMN_TO_QUERY_PARAM[this.sort.active]}`,
Could you please create a `sortMapper` to put this logic inside?
Imagine somedays, the API changes its sorting format, like using a different prefix instead of "-", you must change your code everywhere

2024-08-09 03:46 UTC, LocTran-saritasa commented on apps/angular/src/app/features/anime-table/anime-table.component.ts
> +				debounceTime(500),
Let's create a constant for `500`

2024-08-09 03:46 UTC, LocTran-saritasa commented on apps/angular/src/app/features/anime-table/anime-table.component.ts
> +				startWith({}),
```suggestion
				startWith(null),
```

2024-08-09 03:46 UTC, LocTran-saritasa commented on apps/angular/src/app/features/anime-table/anime-table.component.ts
> +					}).pipe(catchError(() => of(null)))),
It would be better if you show some message or handle this error instead of just returning `null`

2024-08-09 03:46 UTC, LocTran-saritasa commented on apps/angular/src/core/mappers/anime-pagination.mapper.ts
> +}
This mapper should be named `PaginationMapper` instead of sticking to the anime.
If you have another list like a user list, you don't want to re-write the pagination mapper logic for the user right?
```typescript
function fromDto(dto: paginationDto<TDto>, mapper<TModel, TDto>): Pagination<TModel> {
    ....
    results: dto.results.map(mapper),
}
```

2024-08-13 04:22 UTC, LocTran-saritasa approved these changes

2024-08-14 05:46 UTC, danilkukryakov requested changes
Please, improve your code the way we've discussed. Also check my comments and resolve them.
If you have any questions feel free to ping me in Slack.

2024-08-14 05:46 UTC, danilkukryakov commented on apps/angular/src/app/features/anime-table/anime-table.component.ts
> +						return throwError(error);
Such 'throwError' function signature is considered deprecated. Correct solution is the following:
```suggestion
						return throwError(() => error);
```

2024-08-14 05:46 UTC, danilkukryakov commented on apps/angular/src/app/features/anime-table/anime-table.component.ts
> +				}),
When we remove 'startWith(null)' we don't need to check value for 'null' here:
```suggestion
				tap(value => {
					this.totalCount = value.count;
					this.paginator.pageIndex = this.getSubjectValue(this.pageNumber$) ?? 0;

				}),
				map(value => value.results),
```

2024-08-14 05:46 UTC, danilkukryakov commented on apps/angular/src/app/features/anime-table/anime-table.component.ts
> +		this.animeList$ = merge(this.sort.sortChange, this.paginator.page, this.search$, this.filter$)
Let's use `combineLatest` here instead of 'merge'.

2024-08-14 05:46 UTC, danilkukryakov commented on apps/angular/src/app/features/anime-table/anime-table.component.ts
> +				startWith(null),
I guess, we don't need to use 'startWith(null)' here.

Alternatively, you can use some default/initial value here instead of 'null'.

2024-08-14 05:46 UTC, danilkukryakov commented on apps/angular/src/app/features/anime-table/anime-table.component.ts
> +				takeUntilDestroyed(this.destroyRef),
We don't have subscription here that's why we don't need 'takeUntilDestroyed'.
If I'm not mistaken we subscribe to 'animeList$' using 'async' pipe. So we don't need to manage subscription manually. 'takeUntilDestroyed' is a manual subscription management in a sense.

2024-08-14 05:46 UTC, danilkukryakov commented on apps/angular/src/app/features/anime-table/anime-table.component.ts
> +				tap(value => {
We don't need to use nested 'pipe' here:
```suggestion
				}),
				catchError((error: unknown) => {
					this.hasFetchingError$.next(true);
					return throwError(() => error);
				})),
				tap(value => {
```

2024-08-14 05:46 UTC, danilkukryakov commented on apps/angular/src/app/features/anime-table/anime-table.component.ts
> +						this.hasFetchingError$.next(true);
I wonder whether backend send any error message in such case?
Maybe instead of using 'boolean' for showing/hiding fetching error we can display server error message instead.

2024-08-14 05:46 UTC, danilkukryakov commented on apps/angular/src/app/features/anime-table/anime-table.component.ts
> +	}
It's better to avoid 'ngOnChanges' usage where it's possible.
Please, rework it the way we discussed.

2024-08-14 05:46 UTC, danilkukryakov commented on apps/angular/src/app/features/anime-table/anime-table.component.ts
> +			.subscribe(() => this.ordering$.next(SortParamsMapper.toDto(this.sort.active as SortParams, this.sort.direction)));
It's better to avoid direct access of component's inputs. It's better to provide values using Input binding in the template.
To react to changes we should use corresponding Output of the component. We should use Output binding in the template.
In your case it will look like this (as we've discussed):
```html
<mat-paginator
	showFirstLastButtons
	class="paginator"
	[length]="totalCount"
	[pageSizeOptions]="pageSizes"
	[pageIndex]="pageNumber$ | async"
	[pageSize]="pageSize$ | async"
	(page)="onPaginationChange($event)"
/>
```

2024-08-14 05:46 UTC, danilkukryakov commented on apps/angular/src/app/features/anime-table/anime-table.component.ts
> +	protected animeList$ = new Observable<readonly Anime[]>();
Please, rework it the way we've discussed:
```suggestion
	protected readonly animeList$ = this.createAnimeListStream();
```

2024-08-14 05:46 UTC, danilkukryakov commented on apps/angular/src/app/features/anime-table/anime-table.component.ts
> +	private readonly filter$ = new BehaviorSubject<readonly AnimeType[]>([]);
'search' is also a filter. Maybe adjust naming of the 'filter' property to be more clear. Something like this:
```suggestion
	private readonly animeTypesFilter$ = new BehaviorSubject<readonly AnimeType[]>([]);
```

2024-08-14 05:46 UTC, danilkukryakov commented on apps/angular/src/app/features/anime-table/anime-table.component.ts
> +		this.subscribeToControls();
Please, be careful with subscriptions and UI changes in 'ngAfterViewInit'. You might face Angular change detection issues.
'ngAfterViewInit' runs after change detection cycle, that's why we have to call 'markForCheck' manually.

As we've discussed it's possible to rework the solution to avoid 'ngAfterViewInit' usage completely.

2024-08-14 05:46 UTC, danilkukryakov commented on apps/angular/src/app/features/anime-table/anime-table.component.ts
> +	}
Please, try to rework this thing in other places of the project as well.

2024-08-14 05:46 UTC, danilkukryakov commented on apps/angular/src/app/features/anime-table/anime-table.component.ts
> +	private isFiltersChange(previous: string[] | null, current: string[] | null): boolean {
It's better to use `readonly` array in function arguments as our wiki [recommends](https://wiki.saritasa.rocks/frontend/languages/ts-js/best-practices#input):
```suggestion
	private isFiltersChange(previous: readonly string[] | null, current: readonly string[] | null): boolean {
```

2024-08-15 11:07 UTC, AngelinaShmantsar commented on apps/angular/src/app/features/anime-table/anime-table.component.ts
> +						this.hasFetchingError$.next(true);
This error is mainly due to the lack of network

2024-08-16 09:52 UTC, viktor-sakhno-saritasa approved these changes

2024-08-19 07:53 UTC, danilkukryakov requested changes

2024-08-19 07:53 UTC, danilkukryakov commented on apps/angular/src/app/features/anime-type-filter/anime-type-filter.component.ts
> +	protected readonly filterControl = new FormControl<readonly AnimeType[]>(this.types);
In such cases it's better to create custom form control component instead of component with Input/Output properties. It will allow you to use `formControl` directive on your component directly.
In your case it might look like this:
```html
<camp-anime-type-filter [formControl]="filtersForm.animeTypes" />
```
There is an excellent [guide](https://blog.angular-university.io/angular-custom-form-controls/) about custom Angular form controls.

Anyway, for now your solution is good enough, we can leave it without changes. Consider my comment a proposal for future refactoring. Right now you can mark the comment as Resolved.

2024-08-19 07:53 UTC, danilkukryakov commented on apps/angular/src/app/features/paginator/paginator.component.css
> +	z-index: 2;
You have a great comment about 'z-index' in main-page.component.css. Let's add clarification about z-index here as well.

2024-08-19 07:53 UTC, danilkukryakov commented on apps/angular/src/app/features/paginator/paginator.component.ts
> +	public readonly pageEventEmitter = new EventEmitter<PageEvent>();
I think we can be more descriptive here. 'page event' sounds a bit confusing without any context.
What do you think about renaming it to `pageChanged` (or something similar)?

2024-08-19 07:53 UTC, danilkukryakov commented on apps/angular/src/app/features/anime-table/anime-table.component.ts
> +	public readonly sortValueEmitter = new EventEmitter<Sort>();
Usually we don't and 'emitter' or 'eventEmitter' in the Output property name.
We try to use name that refers to event that already happens. For example, `sortChange`, `pageScrolled`, `click`, etc.
The difference is more clear when we compare to solutions and how they will be used:
```html
<camp-anime-table (sortValueEmitter)="onSortChange($event)" />
```
and
```html
<camp-anime-table (sortChange)="onSortChange($event)" />
```
The second option looks better.

Please, adjust naming of the Output properties across your project.

2024-08-19 07:53 UTC, danilkukryakov commented on apps/angular/src/app/pages/main-page.component.ts
> +const DEFAULT_PAGE_NUMBER = 0;
These constants are duplicated three times in your app. Let's try to eliminate code duplication.
One of the possible solution is to declare these constants in a dedicated file. So we can improve them everywhere instead of declaring them each time.

2024-08-19 07:53 UTC, danilkukryakov commented on apps/angular/src/app/pages/main-page.component.ts
> +	}
Usually we try to declare public class members before private ones.
We didn't have such rule in our linter. However, you can use default configuration of [member-ordering](https://typescript-eslint.io/rules/member-ordering/#default-configuration) ESLint rule for reference.

Please, try to adjust ordering of class members where necessary in the project.

2024-08-19 07:53 UTC, danilkukryakov commented on apps/angular/src/app/pages/main-page.component.html
> +/>
It's a bit strange that we display pagination even if table is not visible. Let's adjust the layout:
```suggestion
@if (hasFetchingError$ | async) {
	<h2 class="error">Fetching error occurred!</h2>
} @else {
	<camp-anime-table
		[animeList]="(animeList$ | async) ?? []"
		(sortValueEmitter)="onSortChange($event)"
	/>
	
	<camp-paginator
		[pageSizes]="pageSizes"
		[pageSize]="(pageSize$ | async) ?? 25"
		[pageNumber]="(pageNumber$ | async) ?? 0"
		[totalCount]="totalCount"
		(pageEventEmitter)="onPageEvent($event)"
	/>
}

```

2024-08-19 07:53 UTC, danilkukryakov commented on apps/angular/src/app/pages/main-page.component.ts
> +			}),
You might have some change detection issues with 'totalCount' property. It's better to rework it using reactive primitive (stream or signal).

By the way, the best solution here would be to rework 'totalCount' management in a declarative style (right now you have imperative code).
It might look like this:
```diff
- private createAnimeListStream(): Observable<readonly Anime[]> {
+ private createAnimeListStream(): Observable<Pagination<Anime>> {
```

```html
@if (animeList$ | async; as animeList) {
	<camp-anime-table
		[animeList]="animeList?.results ?? []"
		(sortValueEmitter)="onSortChange($event)"
	/>
	<camp-paginator
		[pageSizes]="pageSizes"
		[pageSize]="(pageSize$ | async) ?? 25"
		[pageNumber]="(pageNumber$ | async) ?? 0"
		[totalCount]="animeList.count"
		(pageEventEmitter)="onPageEvent($event)"
	/>
}
```

2024-08-19 07:53 UTC, danilkukryakov commented on apps/angular/src/core/dtos/anime-management-params.dto.ts
> +	readonly type__in?: string;
If I'm not mistaken we can pass multiple types here. Let's add clarification in JSDoc about such use cases.
As far as I can see we use string with options separated (joined) by comma. Please, add this information in the documentation.

2024-08-19 07:53 UTC, danilkukryakov commented on apps/angular/src/core/models/pagination.ts
> +	readonly previous: string;
'string' here might be confusing without any context. Let's adjust JSDoc to clarify that this 'string' is a link to next/prev page in the paginated list.

2024-08-19 07:53 UTC, danilkukryakov commented on apps/angular/src/core/utils/compose-http-params.ts
> +	return queryParams;
In such cases it's better to use map/reduce.
```suggestion
	return Object.entries(params).reduce((queryParams, [key, value]) => {
		if (params[key] != null) {
			return queryParams.set(key, value);
		}
		return queryParams;
	}, new HttpParams());
```

2024-08-19 07:53 UTC, danilkukryakov commented on apps/angular/src/core/dtos/anime-management-params.dto.ts
> +	readonly offset: string;
Why these properties have 'string' type? I guess `number` should be used here instead:
```suggestion
	/** Limit. */
	readonly limit: number;

	/** Offset. */
	readonly offset: number;
```

2024-08-19 07:53 UTC, danilkukryakov commented on apps/angular/src/app/pages/main-page.component.ts
> +	protected onFilterValueChange(event: readonly AnimeType[]): void {
```suggestion
	 * Handle filter value change.
	 * @param event Type filter change event.
	 */
	protected onFilterValueChange(event: readonly AnimeType[]): void {
```

2024-08-19 07:53 UTC, danilkukryakov commented on apps/angular/src/app/pages/main-page.component.ts
> +	protected onFilterValueChange(event: readonly AnimeType[]): void {
Please, adjust JSDoc comments everywhere.

2024-08-19 07:53 UTC, danilkukryakov commented on apps/angular/src/app/pages/main-page.component.ts
> +		this.ordering$.next(SortParamsMapper.toDto(event.active as SortParams, event.direction));
It's a bit strange that we use DTO in a UI layer.
Let's try to rework 'ordering$' property so it stores `Sort` model rather than some string.

2024-08-19 07:53 UTC, danilkukryakov commented on apps/angular/src/app/features/anime-table/anime-table.component.html
> +		}
Maybe use 'disabled' property of MatSortHeader instead of 'if' statement? (see [docs](https://material.angular.io/components/sort/api#MatSortHeader)).
```suggestion
		<th mat-header-cell *matHeaderCellDef mat-sort-header class="mat-header-cell" [disabled]="!sortableFields.includes(column.key)">{{ column.header }}</th>
```

2024-08-19 07:53 UTC, danilkukryakov commented on apps/angular/src/app/features/anime-type-filter/anime-type-filter.component.html
> +<mat-form-field appearance="outline">
You can set 'appearance' for your form fields globally using `MAT_FORM_FIELD_DEFAULT_OPTIONS` provider.
You can find more information and example in the [docs](https://material.angular.io/components/form-field/overview#form-field-appearance-variants).

2024-08-22 04:40 UTC, danilkukryakov approved these changes

2024-08-22 04:40 UTC, danilkukryakov commented on apps/angular/src/app/features/anime-table/anime-table.component.ts
> +	protected readonly animeList$ = new BehaviorSubject<readonly Anime[]>([]);
It looks like we don't use this property anymore. We can safely remove it.
```suggestion
```

2024-08-22 04:40 UTC, danilkukryakov commented on apps/angular/src/app/features/paginator/paginator.component.ts
> +	public totalCount = 0;
It's more common to declare Input properties first and then Output properties.

2024-08-22 04:40 UTC, danilkukryakov commented on apps/angular/src/app/features/search-form/search-form.component.html
> +<button mat-fab type="button" class="search-button" (click)="onSubmit()">
'onSubmit' sounds a bit confusing here. Maybe rename it `onSearchButtonClick`.

2024-08-22 04:40 UTC, danilkukryakov commented on apps/angular/src/app/pages/main-page.component.ts
> +			}),
Throwing error further might be reasonable in API service. However, it's not a good idea to do so in a component (i.e. UI layer).
If we don't handle this error completely it might break our application (if error boundary is not configured correctly).

In your case you already handle the error - the error is displayed to user in the UI. Since we handle the error there is no need to throw error further. It's common to return `EMPTY` (from RxJS) after error is handled:
```suggestion
			catchError((error: unknown) => {
				this.hasFetchingError$.next(true);
				return EMPTY;
			}),
```

2024-08-22 04:40 UTC, danilkukryakov commented on apps/angular/src/app/features/paginator/paginator.component.html
> +	#paginator
As far as I can see you don't use 'paginator' template reference. You can omit it:
```suggestion
```

2024-08-23 04:30 UTC, merged